#!/usr/bin/env bash
# ============================================================
# server-hardening.sh
# Automated Linux (Ubuntu 22.04 LTS) server hardening script.
# Configures Nginx, UFW firewall, SSH, fail2ban, and SSL.
#
# USAGE:
#   chmod +x server-hardening.sh
#   sudo ./server-hardening.sh
#
# ⚠ WARNING: Run this on a fresh VM first. Test everything
#   before using on any machine you care about.
# ============================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
NC='\033[0m'

step()  { echo -e "\n${BLUE}[STEP]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()  { echo -e "${ORANGE}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ── Root check ───────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  error "Please run this script as root: sudo ./server-hardening.sh"
fi

# ── Configuration variables — change these before running ────
YOUR_DOMAIN="yourdomain.com"          # ← Your actual domain or VM hostname
YOUR_EMAIL="you@email.com"            # ← For Let's Encrypt certificate alerts
SSH_PORT="2222"                       # ← Custom SSH port (NOT 22)
ADMIN_USER="adminuser"                # ← Non-root admin username to create

echo ""
echo "=============================================="
echo "  Linux Server Hardening Script"
echo "  Target: Ubuntu 22.04 LTS"
echo "=============================================="
echo ""
echo -e "${ORANGE}Configuration:${NC}"
echo "  Domain      : $YOUR_DOMAIN"
echo "  Admin User  : $ADMIN_USER"
echo "  SSH Port    : $SSH_PORT"
echo ""
read -rp "Proceed? (yes/no): " confirm
[ "$confirm" != "yes" ] && { echo "Aborted."; exit 0; }

# ─────────────────────────────────────────────────────────────
step "1/10 — Updating system packages"
# ─────────────────────────────────────────────────────────────
apt-get update -y
apt-get upgrade -y
apt-get autoremove -y
ok "System packages updated"

# ─────────────────────────────────────────────────────────────
step "2/10 — Creating admin user (no root login after this)"
# ─────────────────────────────────────────────────────────────
if id "$ADMIN_USER" &>/dev/null; then
  warn "User $ADMIN_USER already exists — skipping creation"
else
  adduser --gecos "" "$ADMIN_USER"
  usermod -aG sudo "$ADMIN_USER"
  ok "User $ADMIN_USER created and added to sudo group"
fi

# Set up SSH key directory for the new user
mkdir -p /home/"$ADMIN_USER"/.ssh
chmod 700 /home/"$ADMIN_USER"/.ssh
chown "$ADMIN_USER":"$ADMIN_USER" /home/"$ADMIN_USER"/.ssh

echo ""
echo -e "${ORANGE}ACTION REQUIRED:${NC}"
echo "On your LOCAL machine (not this server), run:"
echo ""
echo "  ssh-keygen -t ed25519 -C \"$ADMIN_USER@server\""
echo "  cat ~/.ssh/id_ed25519.pub"
echo ""
echo "Then paste your public key below (or press Enter to skip):"
read -rp "Public key: " pub_key

if [ -n "$pub_key" ]; then
  echo "$pub_key" > /home/"$ADMIN_USER"/.ssh/authorized_keys
  chmod 600 /home/"$ADMIN_USER"/.ssh/authorized_keys
  chown "$ADMIN_USER":"$ADMIN_USER" /home/"$ADMIN_USER"/.ssh/authorized_keys
  ok "SSH public key installed for $ADMIN_USER"
else
  warn "No SSH key added. You must add one before disabling password login."
fi

# ─────────────────────────────────────────────────────────────
step "3/10 — Hardening SSH configuration"
# ─────────────────────────────────────────────────────────────
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup
ok "Backed up original SSH config to /etc/ssh/sshd_config.backup"

cat > /etc/ssh/sshd_config <<EOF
# ============================================================
# Hardened SSH Configuration
# Generated by server-hardening.sh
# ============================================================

# Change default port to reduce automated scan noise
Port $SSH_PORT

# Only listen on IPv4
AddressFamily inet

# Authentication settings
PermitRootLogin no                   # Never allow root to SSH in
PasswordAuthentication no            # Keys only — no passwords
PubkeyAuthentication yes             # Enable public key auth
AuthorizedKeysFile .ssh/authorized_keys

# Disable unused and dangerous authentication methods
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no
UsePAM yes

# Restrict login to specific users
AllowUsers $ADMIN_USER

# Session security
LoginGraceTime 30                    # 30 seconds to authenticate
MaxAuthTries 3                       # 3 attempts before disconnect
MaxSessions 3                        # Max concurrent sessions
ClientAliveInterval 300              # Disconnect idle sessions after 5 min
ClientAliveCountMax 2

# Disable X11 and agent forwarding (not needed on a server)
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no

# Use modern, secure ciphers and MACs only
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org

# Log all connections
LogLevel VERBOSE
SyslogFacility AUTH

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

# Validate the config before restarting
sshd -t && ok "SSH config is valid"
systemctl restart sshd
ok "SSH hardened — now running on port $SSH_PORT"
warn "Remember: SSH in with: ssh -p $SSH_PORT $ADMIN_USER@YOUR_SERVER_IP"

# ─────────────────────────────────────────────────────────────
step "4/10 — Configuring UFW firewall"
# ─────────────────────────────────────────────────────────────
apt-get install ufw -y

# Reset to defaults first
ufw --force reset

# Default: deny everything in, allow everything out
ufw default deny incoming
ufw default allow outgoing

# Allow our custom SSH port
ufw allow "$SSH_PORT"/tcp comment 'Custom SSH'

# Allow web traffic
ufw allow 80/tcp  comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'

# Enable the firewall
ufw --force enable

ok "UFW firewall enabled"
echo ""
ufw status verbose

# ─────────────────────────────────────────────────────────────
step "5/10 — Installing and configuring Nginx"
# ─────────────────────────────────────────────────────────────
apt-get install nginx -y
systemctl enable nginx
systemctl start nginx

# Write a secure Nginx config
cat > /etc/nginx/sites-available/default <<'NGINXCONF'
# ── Rate limiting zone (limits requests per IP) ──────────────
limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name DOMAIN_PLACEHOLDER;

    # ── SSL certificate paths (filled in by Certbot) ─────────
    ssl_certificate     /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/privkey.pem;

    # ── SSL hardening ─────────────────────────────────────────
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # ── Security headers ──────────────────────────────────────
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'" always;

    # ── Hide server version ───────────────────────────────────
    server_tokens off;

    # ── Root directory ────────────────────────────────────────
    root /var/www/html;
    index index.html index.htm;

    # ── Rate limiting ─────────────────────────────────────────
    limit_req zone=general burst=20 nodelay;

    location / {
        try_files $uri $uri/ =404;
    }

    # ── Block access to hidden files (.git, .env, etc.) ──────
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # ── Block access to sensitive file extensions ─────────────
    location ~* \.(env|log|sql|bak|config|ini)$ {
        deny all;
    }

    # ── Logging ───────────────────────────────────────────────
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;
}
NGINXCONF

# Replace domain placeholder
sed -i "s/DOMAIN_PLACEHOLDER/$YOUR_DOMAIN/g" /etc/nginx/sites-available/default

nginx -t && ok "Nginx config is valid"
systemctl reload nginx
ok "Nginx configured with security headers and HTTP→HTTPS redirect"

# ─────────────────────────────────────────────────────────────
step "6/10 — Installing SSL certificate (Let's Encrypt / Certbot)"
# ─────────────────────────────────────────────────────────────

# Note: This step only works if:
# 1. Your domain's DNS A record points to this server's IP
# 2. Port 80 is accessible from the internet
# For a VirtualBox VM on your laptop, skip this and use a self-signed cert instead.

apt-get install snapd -y
snap install core; snap refresh core
snap install --classic certbot
ln -sf /snap/bin/certbot /usr/bin/certbot

echo ""
echo -e "${ORANGE}NOTE:${NC} Certbot requires your domain to point to this server's IP."
echo "  If running on a local VM, choose option 2 (self-signed) instead."
echo ""
echo "  1) Run Certbot for real domain: $YOUR_DOMAIN"
echo "  2) Generate self-signed cert (for local VM testing)"
echo "  3) Skip SSL setup"
read -rp "Choose (1/2/3): " ssl_choice

case $ssl_choice in
  1)
    certbot --nginx -d "$YOUR_DOMAIN" --email "$YOUR_EMAIL" \
      --agree-tos --non-interactive --redirect
    ok "Let's Encrypt certificate installed for $YOUR_DOMAIN"
    ;;
  2)
    mkdir -p /etc/letsencrypt/live/"$YOUR_DOMAIN"
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/letsencrypt/live/"$YOUR_DOMAIN"/privkey.pem \
      -out /etc/letsencrypt/live/"$YOUR_DOMAIN"/fullchain.pem \
      -subj "/CN=$YOUR_DOMAIN/O=Lab/C=NG"
    systemctl reload nginx
    ok "Self-signed certificate generated (for testing only)"
    warn "Browsers will show a warning — this is expected for self-signed certs"
    ;;
  3)
    warn "Skipping SSL — server will only serve HTTP until you install a certificate"
    ;;
esac

# ─────────────────────────────────────────────────────────────
step "7/10 — Installing and configuring fail2ban"
# ─────────────────────────────────────────────────────────────
apt-get install fail2ban -y

cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
# Ban attackers for 1 hour after 5 failed attempts
bantime  = 3600
findtime = 600
maxretry = 5
backend  = systemd

# Email notifications (optional — set your email)
destemail = $YOUR_EMAIL
sendername = Fail2Ban
action = %(action_mwl)s

[sshd]
enabled  = true
port     = $SSH_PORT
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3
bantime  = 86400   # Ban SSH brute-force for 24 hours

[nginx-limit-req]
enabled  = true
filter   = nginx-limit-req
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 10

[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 5
EOF

systemctl enable fail2ban
systemctl restart fail2ban
ok "fail2ban configured — SSH brute-force attempts will be auto-banned"

# ─────────────────────────────────────────────────────────────
step "8/10 — Enabling unattended security upgrades"
# ─────────────────────────────────────────────────────────────
apt-get install unattended-upgrades -y
dpkg-reconfigure --priority=low unattended-upgrades
ok "Automatic security updates enabled"

# ─────────────────────────────────────────────────────────────
step "9/10 — Kernel hardening via sysctl"
# ─────────────────────────────────────────────────────────────
cat > /etc/sysctl.d/99-hardening.conf <<'EOF'
# ── Network hardening ─────────────────────────────────────────
# Disable IP forwarding (this is not a router)
net.ipv4.ip_forward = 0

# Protect against SYN flood attacks
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Ignore ICMP broadcast pings (Smurf attack mitigation)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable source validation (prevents IP spoofing)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable IP source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Disable ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1

# ── Memory hardening ──────────────────────────────────────────
# Randomise memory address layout (prevents many exploits)
kernel.randomize_va_space = 2

# Restrict access to kernel logs
kernel.dmesg_restrict = 1

# Restrict ptrace (prevents some privilege escalation)
kernel.yama.ptrace_scope = 1
EOF

sysctl -p /etc/sysctl.d/99-hardening.conf > /dev/null
ok "Kernel hardening parameters applied"

# ─────────────────────────────────────────────────────────────
step "10/10 — Running Lynis security audit"
# ─────────────────────────────────────────────────────────────
apt-get install lynis -y
echo ""
echo -e "${BLUE}Running Lynis audit — this takes ~60 seconds...${NC}"
lynis audit system --quiet 2>/dev/null | tail -20
ok "Lynis audit complete. Full report saved to /var/log/lynis.log"

# ─────────────────────────────────────────────────────────────
echo ""
echo "=============================================="
echo -e "  ${GREEN}Server Hardening Complete!${NC}"
echo "=============================================="
echo ""
echo "Summary of what was configured:"
echo "  ✓ System packages updated"
echo "  ✓ Admin user created: $ADMIN_USER"
echo "  ✓ SSH hardened (port $SSH_PORT, key-only, no root)"
echo "  ✓ UFW firewall: only ports $SSH_PORT, 80, 443 open"
echo "  ✓ Nginx with security headers + HTTPS redirect"
echo "  ✓ SSL certificate installed"
echo "  ✓ fail2ban: auto-bans brute-force attempts"
echo "  ✓ Automatic security updates enabled"
echo "  ✓ Kernel network hardening applied"
echo "  ✓ Lynis audit completed"
echo ""
echo -e "${ORANGE}IMPORTANT — TO RECONNECT AFTER REBOOT:${NC}"
echo "  ssh -p $SSH_PORT $ADMIN_USER@YOUR_SERVER_IP"
echo ""
echo "Completed at $(date)"
echo "=============================================="
